### ISSUE TITLE
Not compatible with: TinyExtraBars.

### ISSUE THREAD

**Issue by Manniala** [SLOKnightfall/BetterWardrobe#106]
Hey, when i open the Apperances i get this (Images), the images were taken before i tested and found what addon that were the "problem".

Items
https://i.imgur.com/wp1b4n6.png

Sets
https://i.imgur.com/FDuurvf.png

Nothing else i can press works, Extra as Saved...

Addon: 
https://www.curseforge.com/wow/addons/tinyextrabars

I can post the lua errors, but there are 25 pages of them (think 4 of them were from TinyExtraBars, since i get 4 when i only run that one), the TEB have not been updated, but it works even tho i get those lua errors, so it might be TEB that breaks your addon, all i know yours and TEB wont work together, each work fine seperately.

**Comment by SLOKnightfall** [comment]
Thanks.  I'll look into it and see what can be done.

**Comment by SLOKnightfall** [comment]
I looked into it and the reason Better Wardrobe breaks is because TinyExtraBars is using an older version of a library that is getting loaded instead of the newer version included in this addon.  To prevent Better wardrobe from breaking copy the LibUIDropDownMenu folder in the BetterWardrobe\Libs directory and use it to replace the version in the TinyExtraBars\Libs directory.

**Comment by SLOKnightfall** [comment]
Looking into this further Ive found that the library that I used to fix the menu taint has a versioning issue where older versions can overwrite the current version if they get loaded after the current version was.  This means that any addon that gets loaded after mine with an old version of the library will break this addon.  Creating a new ticket about the larger issue.

**Comment by Manniala** [comment]
Thx for looking into this :)
Will try to copy the library over, thx again 👍
