### ISSUE TITLE
transmog: item list does not fill space

### ISSUE THREAD

**Issue by Forfold** [SLOKnightfall/BetterWardrobe#139]
**Expected Behavior**
When selecting "Extra Large Transmog Area" from options, I would expect the item area to either:
- Expand to fill the space, showing more items and sets
- Scale to fill the space, showing the same amount of items but fitting better within the frame

**Actual Behavior**
![image](https://user-images.githubusercontent.com/11381794/102637387-c4abbd80-410a-11eb-974c-36761a5a16bf.png)

**Comment by Forfold** [comment]
@SLOKnightfall is this something you are familiar with? I would be happy to contribute if that frame is something we are able to adjust.

**Comment by SLOKnightfall** [comment]
It something I've looked into a bit unfortunately there are a few problems that prevent this from an easy fix. You run into issues trying to scale the item lists because to scale it you would need to reduce the size of the preview window for the needed space.  Trying to have it show more items would require require a large rewrite of code, a lot of which is the default Blizzard code which adds more taint issues. Not to mention increasing the possibility of breaking other addons that refer to the default Blizzard frames.  Also the item list frames are shared between the Transmog vendor and the appearance journal, so any changes made would need to be reverted when showing the appearance journal and adds more complexity/possible errors.

So while doable, its a lot of time/effort to fix a UI issue right now.  For now my focus is getting the outfit DB finished while hopefully getting to playing the game some to. :)

**Comment by Forfold** [comment]
@SLOKnightfall I understand, that makes sense and I appreciate the thoughtful response! I'll go ahead and close this issue, though I may try to work on a POC for this within a fork. Thank you!!
