### ISSUE TITLE
Display bug with the use of the BlizzMove addon

### ISSUE THREAD

**Issue by Tikornu** [SLOKnightfall/BetterWardrobe#210]
When trying to move the transmog window using the BlizzMove addon (allow to move Blizzard windows), the text and features disappear and nothing is clickable anymore. 

![2021-07-12 19_19_26-Window](https://user-images.githubusercontent.com/87331141/125329986-72e8b000-e346-11eb-89a3-289649f6c486.png)

**Comment by solitha** [comment]
Huh,. I came to report something else and got sidetracked by this. I also use BlizzMove.

There was no error and closing and re-opening the window fixed it (although BlizzMove was effectively blocked from working because of it). BUT...

I opened my appearances frame, and moved it... then opened the transmog, and got this error, along with a messy amalgamation of the two frames:

`1x BetterWardrobe\Modules\Wardrobe-Appearances.lua:1175: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WardrobeCollectionFrame:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1175: in function `SetContainer'
[string "@Blizzard_Collections\Blizzard_Wardrobe.lua"]:142: in function <...ceBlizzard_Collections\Blizzard_Wardrobe.lua:140>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2928: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2773: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2641: in function <FrameXML\UIParent.lua:2637>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3492: in function <FrameXML\UIParent.lua:3471>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2083: in function <FrameXML\UIParent.lua:1287>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals:
(*temporary) = WardrobeCollectionFrame {
 GetAppearanceItemHyperlink = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1757
 SetsTab = WardrobeCollectionFrameTab2 {
 }
 searchBox = WardrobeCollectionFrameSearchBox {
 }
 GetActiveTab = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1315
 progressBar = <unnamed> {
 }
 selectedTransmogTab = 1
 ContentFrames = <table> {
 }
 VisualToggle = BetterWardrobeVisualToggle {
 }
 inAlternateForm = false
 OnKeyDown = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1487
 SetContainer = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1159
 OnShow = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1431
 ClickTab = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1203
 ItemsTab = BetterWardrobeCollectionFrameTab1 {
 }
 FilterDropDown = BetterWardrobeFilterDropDown {
 }
 activeFrame = <unnamed> {
 }
 SetSearch = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1806
 HideAppearanceTooltip = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1702
 GetSearchType = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1822
 SetTab = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1210
 UpdateTabButtons = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1530
 SearchBox = WardrobeCollectionFrameSearchBox {
 }
 selectedCollectionTab = 1
 CheckTab = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1195
 RestartSearchTracking = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1792
 SavedSetsTab = BetterWardrobeCollectionFrameTab4 {
 }
 BW_SetsHideSlotButton = <unnamed> {
 }
 RefreshCameras = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1716
 TransmogOptionsButton = BW_TransmogOptionsButton {
 }
 ReloadTab = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1189
 0 = <userdata>
 FilterButton = <unnamed> {
 }
 OnHide = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1463
 SwitchSearchCategory = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1774
 ExtraSetsTab = BetterWardrobeCollectionFrameTab3 {
 }
 GetAppearanceNameTextAndColor = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1722
 SetsCollectionFrame = <unnamed> {
 }
 OnLoad = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1323
 UpdateUsableAppearances = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1709
 ItemsCollectionFrame = <unnamed> {
 }
 SetsTransmogFrame = <unnamed> {
 }
 OnEvent = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1337
 UpdateProgressBar = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1768
 numTabs = 4
 Tabs = <table> {
 }
 SetAppearanceTooltip = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1535
 ClearSearch = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1816
 GetAppearanceSourceTextAndColor = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1741
 selectedTab = 1
 OpenTransmogLink = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:1508
}
(*temporary) = "TOPRIGHT"
(*temporary) = 0
(*temporary) = 0
`

**Comment by SLOKnightfall** [comment]
Fixed in the next update
