### ISSUE TITLE
Appearances tab missing ElvUI skin, small issue with preview window 

### ISSUE THREAD

**Issue by ryanull24** [SLOKnightfall/BetterWardrobe#251]
I looked it up and found a post on Reddit about a year ago saying ElvUI was supported. I don't know if the issue is on my end, but the Appearances tab looks like this to me. Looks like the default UI.

![image](https://user-images.githubusercontent.com/92233600/153729737-776b95dd-ebb9-4634-b8ed-437d29f896f4.png)
![image](https://user-images.githubusercontent.com/92233600/153729767-c42b3188-a70b-443c-af7a-547677205f25.png)

Preview window (Dressing room) looks fine for the most part, except for the overlapping "No Outfit" and duplicate (?) save button

![image](https://user-images.githubusercontent.com/92233600/153729792-a1cd62f6-2bfc-4853-b0f3-1c9fc60e748b.png)

**Comment by pesrou** [comment]
Disable the ElvUI skin for Collections and Dressing Room, that should fix the last issue

**Comment by SLOKnightfall** [comment]
Fixed dressingroom elvui issues

**Comment by ellaerror** [comment]
Hi, I found a solution to this issue. In Plugins/ElvUI.lua of BetterWardrobe there's this code on line 505:
```lua
if not IsAddOnLoaded("Blizzard_Collections") then
	LoadAddOn("Blizzard_Collections")
	C_Timer.After(2, UpdateCollectionFrames)

end
```

By changing the code to this:
```lua
if not IsAddOnLoaded("Blizzard_Collections") then
	LoadAddOn("Blizzard_Collections")
		
end
		
C_Timer.After(2, UpdateCollectionFrames)
```
the issue no longer happens, at least for me. I believe this is because rarity gets loaded first and they also load the addon "Blizzard_Collections" (Rarity/Core/Collections.lua). By doing this, the function `IsAddOnLoaded("Blizzard_Collections")` returns `true`, which causes the `UpdateCollectionFrames` to never be called. I hope this helps.
