### ISSUE TITLE
Some rogue (but not only) sets is broken

### ISSUE THREAD

**Issue by Neurotoxin001** [SLOKnightfall/BetterWardrobe#27]
https://www.wowhead.com/item=168059/ensemble-restless-dreambound-battlegear
Chest is hidden but I have it
![image](https://user-images.githubusercontent.com/39812401/95000402-14c5ba00-05c9-11eb-8ef8-9b09f0e7b0a8.png)

https://www.wowhead.com/item-set=1185/barbed-assassin-battlegear
Head & shoulders is hidden but I have it
![image](https://user-images.githubusercontent.com/39812401/95000410-3cb51d80-05c9-11eb-8d71-e622806cd46a.png)

When I chose "hidden" set my https://www.wowhead.com/item=171333/renowned-explorers-rucksack is still showing
![image](https://user-images.githubusercontent.com/39812401/95000532-4c813180-05ca-11eb-893d-e66a2b983b0f.png)

And here is another little bug:
When I enable "Appearance Preview" and enable "Use custom model - Human Male" I got black character model
![image](https://user-images.githubusercontent.com/39812401/95000557-9bc76200-05ca-11eb-9ff8-1d73fc508eb9.png)

V1.9.1
ruRU wow client

**Comment by SLOKnightfall** [comment]
I'll look into #1 & 2. 

#3 is from me missing adding the "hidden cloak"  id.

#4 The custom race/sex currently uses a "Transmog Model" that uses that dark skin because Blizzard broke something in a previous patch so when you change the race/sex it does not update the character skin so you get a really broken looking model.  Im hoping that the prepatch fixes it.  I'll probably should add a note on the options screen about it.
