### ISSUE TITLE
'UseAction()' Error

### ISSUE THREAD

**Issue by darbiirue** [SLOKnightfall/BetterWardrobe#316]
The following error occurred when I was using Soar on my Evoker, followed by trying to use Skyward Ascent / Surge Forward. It results in WoW asking to disable the addon.

`1x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterWardrobe' tried to call the protected function 'UseAction()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/ActionButton.lua"]:144: in function `ActionButtonDown'
[string "ACTIONBUTTON1"]:2: in function <[string "ACTIONBUTTON1"]:1>`

**Comment by SLOKnightfall** [comment]
Its being caused by all the taint issues the new UI caused. Its most likely being caused by some other addon tainting this addon. If you disable this addon and clear buggrabbers cache you'll probably see the same error with some other addon listed. I've run this addon by its self while questing & doing dungeons and haven't encountered the issue you are reporting. At this time there is nothing really that can be done.
