### ISSUE TITLE
Protected Issue ... (again)

### ISSUE THREAD

**Issue by DePhoegon** [SLOKnightfall/BetterWardrobe#319]
It happens after using the xmog station to do something, then in some instance combat.   It's so bloody annoying.
```
2x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterWardrobe' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR1BUTTON6"]:2: in function <[string "MULTIACTIONBAR1BUTTON6"]:1>

**Comment by SLOKnightfall** [comment]
Its being caused by all the taint issues the new UI caused.  Its most likely being caused by some other addon tainting this addon.  If you disable this addon and clear buggrabbers cache you'll probably see the same error with some other addon listed.  I've run this addon by its self while questing & doing dungeons and haven't encountered the issue you are reporting.  At this time there is nothing really that can be done.

**Comment by DePhoegon** [comment]
No,   it hasn't happened with any other addon.    The only unstable addon I've had was astralkeys (which I stopped using because of a friends list).  Though I'm sure that's the only issue & nothing to do with this on.    No reason to not believe you.. but 'taint bug from blizzard new ui is to blame' kinda sounds like blaming the controller.

**Comment by SLOKnightfall** [comment]
Previously taint didn't affect things as much since everything was somewhat self contained.  Most addon authors didn't really need to care about it or are even really aware of it.   Now when you active the new moveable UI if any of the windows that can now be moved has been tainted that taint gets spread to all UI editor and all the windows it controls. Once everything is tainted, any addon that interacts with them becomes tainted too.   I've seen a bunch of people posting macros or new addons to reposition other UI elements by overwriting the frames event handlers which then taints the UI element, which then spreads.  

 Buggrabber is not completely reliable at determine the cause of blocked actions since 1) the addon is lists is not always the source of the taint, as you need to pour through the taint log to actually trace it back to the source 2) buggabber tends to combine similar errors so at one time it may be addon A that is being reported, and then another time it may be addon B.  Since the errors are similar buggrabber just redisplays the initial error and adds to the count.

I've found that the useaction error you are reporting is usually caused by some addon using the Blizzard API to create dropdown window.  Blizzards API is written so that a global variable is set when the user selects something from a menu, unfortunately if non blizzard code uses it then that global variable gets tainted and every ui element that has a dropdown menu gets tainted too.  I actually use a dropdown menu library to specifically prevent the global variable taint issue.  As this addon is attached to the collections journal which uses dropdowns, once the dropdowns are tainted, that taint spreads to the collection journal and then to my addon.
