### ISSUE TITLE
Applying Saved Transmogs ends up with hidden slots

### ISSUE THREAD

**Issue by RedAntisocial** [SLOKnightfall/BetterWardrobe#326]
Version 4.4.9
All new saved transmogs result in hidden shoulders, belts, and gloves when applied.

**Comment by Adoil1312** [comment]
Version 4.6.3
Similar problem with some of my characters. Shoulders and feet transmogs are set to hidden when applying a saved outfit to my warrrior. Same problem but only with belt on my rogue. Transmogs on other characters working correctly (so far).

**Comment by Ketrel** [comment]
I have the same issue.  Usually with chest pieces.  It's been for a number of versions but still persists in 4.6.3

**Comment by SLOKnightfall** [comment]
I've been trying to figure this out and have not been able to get the issue to appear for me.  Can you check that the option to hide specific items hasn't been enabled some how.  From the transmog vendor click on the little helm icon to the right of the save button.

**Comment by Adoil1312** [comment]
> I've been trying to figure this out and have not been able to get the issue to appear for me. Can you check that the option to hide specific items hasn't been enabled some how. From the transmog vendor click on the little helm icon to the right of the save button.

I've just checked and that's not causing the problem for me, sorry. Even then, if it was that would just raise further questions because I've never engaged with the "hide item slot" feature before anyway.
![Screenshot 2023-01-15 11 08 07](https://user-images.githubusercontent.com/122325584/212562752-75d1f846-657a-4725-99dc-990e303f4473.png)

Is it worth noting that in the shoulder slot (and presumably feet, but they're too low to see) still shows on the saved outfit preview?
![Screenshot 2023-01-15 11 20 27](https://user-images.githubusercontent.com/122325584/212562917-5eab1b7c-4e67-405f-ae32-3bc61ea88749.png)

**Comment by Ketrel** [comment]
Here's some pieces I know offhand won't apply from a saved mog

Black Valdrakken Pants  
Bronze Valdrakken Jacket  
Pauldrens of Winged Triumph (Raid Finder Color)  
Legplates of Unthinking Strife

Those are some I know offhand won't apply from a saved mog.

**Comment by RedAntisocial** [comment]
> I've been trying to figure this out and have not been able to get the issue to appear for me. Can you check that the option to hide specific items hasn't been enabled some how. From the transmog vendor click on the little helm icon to the right of the save button.

I can confirm that I don't have any of the slots that are being hidden set to hide.

I can take as look at specific slots again this evening.

**Comment by Ketrel** [comment]
I can also confirm no slots are set to hide

**Comment by Ketrel** [comment]
Sure, Marquista is the toon I was referencing the issue with here: https://github.com/SLOKnightfall/BetterWardrobe/issues/326#issuecomment-1383261020

**Comment by Ketrel** [comment]
[BetterWardrobe.txt](https://github.com/SLOKnightfall/BetterWardrobe/files/10483538/BetterWardrobe.txt)
Had to rename it to txt to upload.

**Comment by RedAntisocial** [comment]
[RedAnti_BetterWardrobe.txt](https://github.com/SLOKnightfall/BetterWardrobe/files/10485692/RedAnti_BetterWardrobe.txt)
### Character: Periago
Set: Black Dragonflight
Hidden Pieces: Chest and Boots

Set: DF Blue and Gold
Hidden Pieces: Boots

### Character: Renfys
Set: Waiting for Tier
Hidden Pieces: Shoulders, Chest, Bracers, Boots

**Comment by Adoil1312** [comment]
[Adoil_BetterWardrobe.txt](https://github.com/SLOKnightfall/BetterWardrobe/files/10497724/Adoil_BetterWardrobe.txt)

Character: Lleucu
Set: Radiant Rage
Hidden: Shoulders, Boots

And a strange bit that hopefully helps
Character: Quitter
Set: Blood in the Water
Hidden: none now, but the Belt slot used to be hidden
(I don't know what I did to fix Quitter's set, because as far as I can tell I've tried all the same things with Lleucu and her set it still borked)

**Comment by SLOKnightfall** [comment]
Thanks for all the help.  I think that I tracked down the issue and it should be fixed in the next update.
