### ISSUE TITLE
AddOn Integration Request

### ISSUE THREAD

**Issue by SisterSkaoi** [SLOKnightfall/BetterWardrobe#354]
Hi, I realise this is a long shot but may as well ask!

I prefer the way the WardrobeSort addon (https://github.com/ketho-wow/WardrobeSort) sorts my collection & displays the item ID when in the collections window. Is it possible to either set BetterWardrobe to *not* override sorting when that addon is present, or possibly enquire with that addon's author to integrate it with credit? 

For a long time WardrobeSort was all I wanted on its own, and for a lot of people that's definitely all the need, but now I want to use both and find that BetterWardrobe overrides it.

Thanks for considering! -Skaoi

**Comment by SLOKnightfall** [comment]
Better Wardrobe uses custom frames for all the transmog collection windows, which is why WardrobeSort does not work with it.  BetterWardrobe already has many of the same sorting options. The next update will add the ability to sort by ilevel and item id.  Additionally I've added the options to add itemID, ILevel, and visual IDs to the tooltips in the collection window.
