### ISSUE TITLE
KkthnxUI conflict, bags don't sort initially and more

### ISSUE THREAD

**Issue by Kkthnx** [SLOKnightfall/BetterWardrobe#433]
I've been using your addon along with my UI (KkthnxUI), and I've noticed that my bags don't sort initially. I have to close and reopen the bags for them to display correctly. I've tested this several times with your addon enabled. Here's what's happening:

Normally, when I open my bags, they should look like this:
https://i.imgur.com/GQYP2DX.png

However, when I enable your addon, my bags end up like this instead:
https://i.imgur.com/1M2ojIV.png

To resolve this issue, I have to close and reopen the bags again.

I'm not sure how your addon is conflicting with my cargbags in KkthnxUI. Could you provide some insight? I'm currently at a loss on how to fix it.

If you want you can reach me on Discord @ Kkthnx.

**Comment by SLOKnightfall** [comment]
So a while back I had similar wierd interactions with Baganon.  After some digging I found it was from parsing tooltip data using its global name which was causing the issue by triggering data refreshes every time a tooltip was processed. I see that you are referencing global tooltip names in your addon which may be the issue

It turns out that there are now a tooltip data handler that you can use to get tooltip data.

Try 
`function Module:GetLevelLine()
	local tooltipData = GameTooltip:GetTooltipData()
	for i=1, #tooltipData.lines do  
		local linetext = tooltipData.lines[i].leftText
		if not tiptext then
			break
		end
		if linetext and strfind(linetext, LEVEL) then
			return tiptext
		end
	end
end`
 
Hopefully that fixes things for you.

**Comment by Kkthnx** [comment]
Thank you kindly for your feedback. I will give this a look. Again, thank you!

**Comment by Kkthnx** [comment]
Sadly, that did not resolve the issue but I am going to go through my UI and code base and switch a lot of parsing.

https://i.imgur.com/Urz0DHZ.jpeg

**Comment by SLOKnightfall** [comment]
Sorry to hear that didn't resolve the issue.  Best luck with your updates
